# 
#
#

JAVA = java
JAVAC = javac
#JAVAC = jikes
#JAVAC_ARGS = -g $(BASEDIR)/generated:$(CLASSPATH)

# following class path is for CygWin bash
JAVAC_ARGS = -g:none -classpath "$(BASEDIR)/src;$(BASEDIR)/generated;$(CLASSPATH)"
GEN_JAVAC_ARGS = -g:none -classpath "../src;$(CLASSPATH)"

FIND=find
TAR=tar
JAR=jar

#XT=${JAVA} com.jclark.xsl.sax.Driver
XALAN=${JAVA} org.apache.xalan.xslt.Process

JAVADOC = javadoc
JAVADOC_ARGS = -overview $(BASEDIR)/src/overview.html -sourcepath "$(BASEDIR)/src;$(BASEDIR)/generated" -classpath "$(BASEDIR)/src;$(BASEDIR)/generated;$(CLASSPATH)" -d $(APIDOCDIR)

TARGETS = all clean clobber

.SUFFIXES: .java .class .xml $(SUFFIXES)

.java.class:
	$(JAVAC) $(JAVAC_ARGS) $<

