/*
 * $Id$
 * Copyright (C) 2001-2002 The Apache Software Foundation. All rights reserved.
 * For details on use and redistribution please refer to the
 * LICENSE file included with these sources.
 * @author <a href="mailto:pbwest@powerup.com.au">Peter B. West</a>
 * @version $Revision$ $Name$
 */

package org.apache.fop.fo;

import org.apache.fop.fo.expr.PropertyException;

/**
 * A class of constants; an array of all property names and the constants
 * by which to refer to them.
 */

public class PropNames {

    private static final String tag = "$Name$";
    private static final String revision = "$Revision$";

    /*
     * List of property constants in property processing order -
     * FONT, FONT_SIZE first
     * Shorthands must precede any of their expansion elements.
     * Compounds must precede any of their components.
     * The list of property constants can be regenerated in XEmacs by setting
     * the region on the list of constants. (C-Space at the beginning,
     * move to last line, C-x C-x to exchange mark and point.)  Then run
     * a shell command on the region with replacement (M-1 M-|).  Use
     * the perl command:
     * perl -p -e 'BEGIN{$n=0};$n++ if s/= [0-9]+,/= $n,/'
     * Alternatively, start at a given point in the list by setting the
     * appropriate start value for $n.
     *
     * in vi, set mark `a' at the last line and
     * !'aperl... etc
     */
     /** Constant for matching property defined in <i>XSLFO</i>. */

    public static final int
                                    NO_PROPERTY = 0,
            // Properties setting font-size first
            // Shorthand first
                                           FONT = 1,
                                      FONT_SIZE = 2,
            // All other shorthands
                                     BACKGROUND = 3,
                            BACKGROUND_POSITION = 4,
                                         BORDER = 5,
                                   BORDER_COLOR = 6,
                                   BORDER_STYLE = 7,
                                   BORDER_WIDTH = 8,
                                  BORDER_BOTTOM = 9,
                                    BORDER_LEFT = 10,
                                   BORDER_RIGHT = 11,
                                     BORDER_TOP = 12,
                                 BORDER_SPACING = 13,
                                            CUE = 14,
                                         MARGIN = 15,
                                        PADDING = 16,
                               PAGE_BREAK_AFTER = 17,
                              PAGE_BREAK_BEFORE = 18,
                              PAGE_BREAK_INSIDE = 19,
                                          PAUSE = 20,
                                       POSITION = 21,
                                           SIZE = 22,
                                 VERTICAL_ALIGN = 23,
                                    WHITE_SPACE = 24,
                                       XML_LANG = 25,
            // Non-shorthand properties
            // Within these, compounds precede their components
            // and corresponding relative properties
            // precede corresponding absolute properties
                              ABSOLUTE_POSITION = 26,
                                   ACTIVE_STATE = 27,
                               ALIGNMENT_ADJUST = 28,
                             ALIGNMENT_BASELINE = 29,
                                   AUTO_RESTORE = 30,
                                        AZIMUTH = 31,
                          BACKGROUND_ATTACHMENT = 32,
                               BACKGROUND_COLOR = 33,
                               BACKGROUND_IMAGE = 34,
                 BACKGROUND_POSITION_HORIZONTAL = 35,
                   BACKGROUND_POSITION_VERTICAL = 36,
                              BACKGROUND_REPEAT = 37,
                                 BASELINE_SHIFT = 38,
                             BLANK_OR_NOT_BLANK = 39,
                    BLOCK_PROGRESSION_DIMENSION = 40,
            BLOCK_PROGRESSION_DIMENSION_MINIMUM = 41,
            BLOCK_PROGRESSION_DIMENSION_OPTIMUM = 42,
            BLOCK_PROGRESSION_DIMENSION_MAXIMUM = 43,

        // Border corresponding properties
                             BORDER_AFTER_COLOR = 44,
                        BORDER_AFTER_PRECEDENCE = 45,
                             BORDER_AFTER_STYLE = 46,
                             BORDER_AFTER_WIDTH = 47,
                      BORDER_AFTER_WIDTH_LENGTH = 48,
              BORDER_AFTER_WIDTH_CONDITIONALITY = 49,
                            BORDER_BEFORE_COLOR = 50,
                       BORDER_BEFORE_PRECEDENCE = 51,
                            BORDER_BEFORE_STYLE = 52,
                            BORDER_BEFORE_WIDTH = 53,
                     BORDER_BEFORE_WIDTH_LENGTH = 54,
             BORDER_BEFORE_WIDTH_CONDITIONALITY = 55,
                               BORDER_END_COLOR = 56,
                          BORDER_END_PRECEDENCE = 57,
                               BORDER_END_STYLE = 58,
                               BORDER_END_WIDTH = 59,
                        BORDER_END_WIDTH_LENGTH = 60,
                BORDER_END_WIDTH_CONDITIONALITY = 61,
                             BORDER_START_COLOR = 62,
                        BORDER_START_PRECEDENCE = 63,
                             BORDER_START_STYLE = 64,
                             BORDER_START_WIDTH = 65,
                      BORDER_START_WIDTH_LENGTH = 66,
              BORDER_START_WIDTH_CONDITIONALITY = 67,

                            BORDER_BOTTOM_COLOR = 68,
                            BORDER_BOTTOM_STYLE = 69,
                            BORDER_BOTTOM_WIDTH = 70,
                              BORDER_LEFT_COLOR = 71,
                              BORDER_LEFT_STYLE = 72,
                              BORDER_LEFT_WIDTH = 73,
                             BORDER_RIGHT_COLOR = 74,
                             BORDER_RIGHT_STYLE = 75,
                             BORDER_RIGHT_WIDTH = 76,
                               BORDER_TOP_COLOR = 77,
                               BORDER_TOP_STYLE = 78,
                               BORDER_TOP_WIDTH = 79,

                                BORDER_COLLAPSE = 80,
                              BORDER_SEPARATION = 81,
  BORDER_SEPARATION_BLOCK_PROGRESSION_DIRECTION = 82,
 BORDER_SEPARATION_INLINE_PROGRESSION_DIRECTION = 83,
                                         BOTTOM = 84,
                                    BREAK_AFTER = 85,
                                   BREAK_BEFORE = 86,
                                   CAPTION_SIDE = 87,
                                      CASE_NAME = 88,
                                     CASE_TITLE = 89,
                                      CHARACTER = 90,
                                          CLEAR = 91,
                                           CLIP = 92,
                                          COLOR = 93,
                             COLOR_PROFILE_NAME = 94,
                                   COLUMN_COUNT = 95,
                                     COLUMN_GAP = 96,
                                  COLUMN_NUMBER = 97,
                                   COLUMN_WIDTH = 98,
                                 CONTENT_HEIGHT = 99,
                                   CONTENT_TYPE = 100,
                                  CONTENT_WIDTH = 101,
                                        COUNTRY = 102,
                                      CUE_AFTER = 103,
                                     CUE_BEFORE = 104,
                   DESTINATION_PLACEMENT_OFFSET = 105,
                                      DIRECTION = 106,
                                  DISPLAY_ALIGN = 107,
                              DOMINANT_BASELINE = 108,
                                      ELEVATION = 109,
                                    EMPTY_CELLS = 110,
                                     END_INDENT = 111,
                                       ENDS_ROW = 112,
                                         EXTENT = 113,
                           EXTERNAL_DESTINATION = 114,
                                          FLOAT = 115,
                                      FLOW_NAME = 116,
                                    FONT_FAMILY = 117,
                        FONT_SELECTION_STRATEGY = 118,
                               FONT_SIZE_ADJUST = 119,
                                   FONT_STRETCH = 120,
                                     FONT_STYLE = 121,
                                   FONT_VARIANT = 122,
                                    FONT_WEIGHT = 123,
                               FORCE_PAGE_COUNT = 124,
                                         FORMAT = 125,
                   GLYPH_ORIENTATION_HORIZONTAL = 126,
                     GLYPH_ORIENTATION_VERTICAL = 127,
                             GROUPING_SEPARATOR = 128,
                                  GROUPING_SIZE = 129,
                                         HEIGHT = 130,
                                      HYPHENATE = 131,
                          HYPHENATION_CHARACTER = 132,
                               HYPHENATION_KEEP = 133,
                       HYPHENATION_LADDER_COUNT = 134,
               HYPHENATION_PUSH_CHARACTER_COUNT = 135,
             HYPHENATION_REMAIN_CHARACTER_COUNT = 136,
                                             ID = 137,
                           INDICATE_DESTINATION = 138,
                            INITIAL_PAGE_NUMBER = 139,
                   INLINE_PROGRESSION_DIMENSION = 140,
           INLINE_PROGRESSION_DIMENSION_MINIMUM = 141,
           INLINE_PROGRESSION_DIMENSION_OPTIMUM = 142,
           INLINE_PROGRESSION_DIMENSION_MAXIMUM = 143,
                           INTERNAL_DESTINATION = 144,
                             INTRUSION_DISPLACE = 145,
                                  KEEP_TOGETHER = 146,
                      KEEP_TOGETHER_WITHIN_LINE = 147,
                      KEEP_TOGETHER_WITHIN_PAGE = 148,
                    KEEP_TOGETHER_WITHIN_COLUMN = 149,
                                 KEEP_WITH_NEXT = 150,
                     KEEP_WITH_NEXT_WITHIN_LINE = 151,
                     KEEP_WITH_NEXT_WITHIN_PAGE = 152,
                   KEEP_WITH_NEXT_WITHIN_COLUMN = 153,
                             KEEP_WITH_PREVIOUS = 154,
                 KEEP_WITH_PREVIOUS_WITHIN_LINE = 155,
                 KEEP_WITH_PREVIOUS_WITHIN_PAGE = 156,
               KEEP_WITH_PREVIOUS_WITHIN_COLUMN = 157,
                                       LANGUAGE = 158,
                           LAST_LINE_END_INDENT = 159,
                               LEADER_ALIGNMENT = 160,
                                  LEADER_LENGTH = 161,
                          LEADER_LENGTH_MINIMUM = 162,
                          LEADER_LENGTH_OPTIMUM = 163,
                          LEADER_LENGTH_MAXIMUM = 164,
                                 LEADER_PATTERN = 165,
                           LEADER_PATTERN_WIDTH = 166,
                                           LEFT = 167,
                                 LETTER_SPACING = 168,
                                   LETTER_VALUE = 169,
                             LINEFEED_TREATMENT = 170,
                                    LINE_HEIGHT = 171,
                            LINE_HEIGHT_MINIMUM = 172,
                            LINE_HEIGHT_OPTIMUM = 173,
                            LINE_HEIGHT_MAXIMUM = 174,
                     LINE_HEIGHT_CONDITIONALITY = 175,
                         LINE_HEIGHT_PRECEDENCE = 176,
                   LINE_HEIGHT_SHIFT_ADJUSTMENT = 177,
                         LINE_STACKING_STRATEGY = 178,

                              MARKER_CLASS_NAME = 179,
                                    MASTER_NAME = 180,
                               MASTER_REFERENCE = 181,
                                     MAX_HEIGHT = 182,
                                MAXIMUM_REPEATS = 183,
                                      MAX_WIDTH = 184,
                                    MEDIA_USAGE = 185,
                                     MIN_HEIGHT = 186,
                                      MIN_WIDTH = 187,
                        NUMBER_COLUMNS_REPEATED = 188,
                         NUMBER_COLUMNS_SPANNED = 189,
                            NUMBER_ROWS_SPANNED = 190,
                                    ODD_OR_EVEN = 191,
                                        ORPHANS = 192,
                                       OVERFLOW = 193,

        // Padding corresponding properties
                                  PADDING_AFTER = 194,
                           PADDING_AFTER_LENGTH = 195,
                   PADDING_AFTER_CONDITIONALITY = 196,
                                 PADDING_BEFORE = 197,
                          PADDING_BEFORE_LENGTH = 198,
                  PADDING_BEFORE_CONDITIONALITY = 199,
                                    PADDING_END = 200,
                             PADDING_END_LENGTH = 201,
                     PADDING_END_CONDITIONALITY = 202,
                                  PADDING_START = 203,
                           PADDING_START_LENGTH = 204,
                   PADDING_START_CONDITIONALITY = 205,

                                 PADDING_BOTTOM = 206,
                                   PADDING_LEFT = 207,
                                  PADDING_RIGHT = 208,
                                    PADDING_TOP = 209,

                                    PAGE_HEIGHT = 210,
                                  PAGE_POSITION = 211,
                                     PAGE_WIDTH = 212,
                                    PAUSE_AFTER = 213,
                                   PAUSE_BEFORE = 214,
                                          PITCH = 215,
                                    PITCH_RANGE = 216,
                                    PLAY_DURING = 217,
                                     PRECEDENCE = 218,
            PROVISIONAL_DISTANCE_BETWEEN_STARTS = 219,
                   PROVISIONAL_LABEL_SEPARATION = 220,
                          REFERENCE_ORIENTATION = 221,
                                         REF_ID = 222,
                                    REGION_NAME = 223,
                                 RELATIVE_ALIGN = 224,
                              RELATIVE_POSITION = 225,
                               RENDERING_INTENT = 226,
                              RETRIEVE_BOUNDARY = 227,
                            RETRIEVE_CLASS_NAME = 228,
                              RETRIEVE_POSITION = 229,
                                       RICHNESS = 230,
                                          RIGHT = 231,
                                           ROLE = 232,
                                     RULE_STYLE = 233,
                                 RULE_THICKNESS = 234,
                                        SCALING = 235,
                                 SCALING_METHOD = 236,
                                   SCORE_SPACES = 237,
                                         SCRIPT = 238,
                               SHOW_DESTINATION = 239,
                                SOURCE_DOCUMENT = 240,

        // Space/margin corresponding properties
                                    SPACE_AFTER = 241,
                            SPACE_AFTER_MINIMUM = 242,
                            SPACE_AFTER_OPTIMUM = 243,
                            SPACE_AFTER_MAXIMUM = 244,
                     SPACE_AFTER_CONDITIONALITY = 245,
                         SPACE_AFTER_PRECEDENCE = 246,
                                   SPACE_BEFORE = 247,
                           SPACE_BEFORE_MINIMUM = 248,
                           SPACE_BEFORE_OPTIMUM = 249,
                           SPACE_BEFORE_MAXIMUM = 250,
                    SPACE_BEFORE_CONDITIONALITY = 251,
                        SPACE_BEFORE_PRECEDENCE = 252,
                                      SPACE_END = 253,
                              SPACE_END_MINIMUM = 254,
                              SPACE_END_OPTIMUM = 255,
                              SPACE_END_MAXIMUM = 256,
                       SPACE_END_CONDITIONALITY = 257,
                           SPACE_END_PRECEDENCE = 258,
                                    SPACE_START = 259,
                            SPACE_START_MINIMUM = 260,
                            SPACE_START_OPTIMUM = 261,
                            SPACE_START_MAXIMUM = 262,
                     SPACE_START_CONDITIONALITY = 263,
                         SPACE_START_PRECEDENCE = 264,

                                  MARGIN_BOTTOM = 265,
                                    MARGIN_LEFT = 266,
                                   MARGIN_RIGHT = 267,
                                     MARGIN_TOP = 268,

                                           SPAN = 269,
                                          SPEAK = 270,
                                   SPEAK_HEADER = 271,
                                  SPEAK_NUMERAL = 272,
                              SPEAK_PUNCTUATION = 273,
                                    SPEECH_RATE = 274,
                                            SRC = 275,
                                   START_INDENT = 276,
                                 STARTING_STATE = 277,
                                     STARTS_ROW = 278,
                                         STRESS = 279,
                         SUPPRESS_AT_LINE_BREAK = 280,
                                      SWITCH_TO = 281,
                                   TABLE_LAYOUT = 282,
                     TABLE_OMIT_FOOTER_AT_BREAK = 283,
                     TABLE_OMIT_HEADER_AT_BREAK = 284,
                    TARGET_PRESENTATION_CONTEXT = 285,
                      TARGET_PROCESSING_CONTEXT = 286,
                              TARGET_STYLESHEET = 287,
                                     TEXT_ALIGN = 288,
                                TEXT_ALIGN_LAST = 289,
                                  TEXT_ALTITUDE = 290,
                                TEXT_DECORATION = 291,
                                     TEXT_DEPTH = 292,
                                    TEXT_INDENT = 293,
                                    TEXT_SHADOW = 294,
                                 TEXT_TRANSFORM = 295,
                                            TOP = 296,
                            TREAT_AS_WORD_SPACE = 297,
                                   UNICODE_BIDI = 298,
                                     VISIBILITY = 299,
                                   VOICE_FAMILY = 300,
                                         VOLUME = 301,
                           WHITE_SPACE_COLLAPSE = 302,
                          WHITE_SPACE_TREATMENT = 303,
                                         WIDOWS = 304,
                                          WIDTH = 305,
                                   WORD_SPACING = 306,
                           WORD_SPACING_MINIMUM = 307,
                           WORD_SPACING_OPTIMUM = 308,
                           WORD_SPACING_MAXIMUM = 309,
                    WORD_SPACING_CONDITIONALITY = 310,
                        WORD_SPACING_PRECEDENCE = 311,
                                    WRAP_OPTION = 312,
                                   WRITING_MODE = 313,
                                        Z_INDEX = 314,
        
                            LAST_PROPERTY_INDEX = Z_INDEX;


    /**
     * A String[] array containing the names of all of the FO properties.
     * The array is effectively 1-based, as the first element is null.
     * The list of int constants referring to the properties must be manually
     * kept in sync with the names in this array, as the constants can be
     * used to index into this, and the other property arrays.
     */

    private static final String[] propertyNames = {
        "no-property",
        "font",
        "font-size",

        "background",
        "background-position",
        "border",
        "border-color",
        "border-style",
        "border-width",
        "border-bottom",
        "border-left",
        "border-right",
        "border-top",
        "border-spacing",
        "cue",
        "margin",
        "padding",
        "page-break-after",
        "page-break-before",
        "page-break-inside",
        "pause",
        "position",
        "size",
        "vertical-align",
        "white-space",
        "xml:lang",

        "absolute-position",
        "active-state",
        "alignment-adjust",
        "alignment-baseline",
        "auto-restore",
        "azimuth",
        "background-attachment",
        "background-color",
        "background-image",
        "background-position-horizontal",
        "background-position-vertical",
        "background-repeat",
        "baseline-shift",
        "blank-or-not-blank",
        "block-progression-dimension",
        "block-progression-dimension.minimum",
        "block-progression-dimension.optimum",
        "block-progression-dimension.maximum",

        "border-after-color",
        "border-after-precedence",
        "border-after-style",
        "border-after-width",
        "border-after-width.length",
        "border-after-width.conditionality",
        "border-before-color",
        "border-before-precedence",
        "border-before-style",
        "border-before-width",
        "border-before-width.length",
        "border-before-width.conditionality",
        "border-end-color",
        "border-end-precedence",
        "border-end-style",
        "border-end-width",
        "border-end-width.length",
        "border-end-width.conditionality",
        "border-start-color",
        "border-start-precedence",
        "border-start-style",
        "border-start-width",
        "border-start-width.length",
        "border-start-width.conditionality",

        "border-bottom-color",
        "border-bottom-style",
        "border-bottom-width",
        "border-left-color",
        "border-left-style",
        "border-left-width",
        "border-right-color",
        "border-right-style",
        "border-right-width",
        "border-top-color",
        "border-top-style",
        "border-top-width",

        "border-collapse",
        "border-separation",
        "border-separation.block-progression-direction",
        "border-separation.inline-progression-direction",
        "bottom",
        "break-after",
        "break-before",
        "caption-side",
        "case-name",
        "case-title",
        "character",
        "clear",
        "clip",
        "color",
        "color-profile-name",
        "column-count",
        "column-gap",
        "column-number",
        "column-width",
        "content-height",
        "content-type",
        "content-width",
        "country",
        "cue-after",
        "cue-before",
        "destination-placement-offset",
        "direction",
        "display-align",
        "dominant-baseline",
        "elevation",
        "empty-cells",
        "end-indent",
        "ends-row",
        "extent",
        "external-destination",
        "float",
        "flow-name",
        "font-family",
        "font-selection-strategy",
        "font-size-adjust",
        "font-stretch",
        "font-style",
        "font-variant",
        "font-weight",
        "force-page-count",
        "format",
        "glyph-orientation-horizontal",
        "glyph-orientation-vertical",
        "grouping-separator",
        "grouping-size",
        "height",
        "hyphenate",
        "hyphenation-character",
        "hyphenation-keep",
        "hyphenation-ladder-count",
        "hyphenation-push-character-count",
        "hyphenation-remain-character-count",
        "id",
        "indicate-destination",
        "initial-page-number",
        "inline-progression-dimension",
        "inline-progression-dimension.minimum",
        "inline-progression-dimension.optimum",
        "inline-progression-dimension.maximum",
        "internal-destination",
        "intrusion-displace",
        "keep-together",
        "keep-together.within-line",
        "keep-together.within-column",
        "keep-together.within-page",
        "keep-with-next",
        "keep-with-next.within-line",
        "keep-with-next.within-column",
        "keep-with-next.within-page",
        "keep-with-previous",
        "keep-with-previous.within-line",
        "keep-with-previous.within-column",
        "keep-with-previous.within-page",
        "language",
        "last-line-end-indent",
        "leader-alignment",
        "leader-length",
        "leader-length.minimum",
        "leader-length.optimum",
        "leader-length.maximum",
        "leader-pattern",
        "leader-pattern-width",
        "left",
        "letter-spacing",
        "letter-value",
        "linefeed-treatment",
        "line-height",
        "line-height.minimum",
        "line-height.optimum",
        "line-height.maximum",
        "line-height.conditionality",
        "line-height.precedence",
        "line-height-shift-adjustment",
        "line-stacking-strategy",

        "marker-class-name",
        "master-name",
        "master-reference",
        "max-height",
        "maximum-repeats",
        "max-width",
        "media-usage",
        "min-height",
        "min-width",
        "number-columns-repeated",
        "number-columns-spanned",
        "number-rows-spanned",
        "odd-or-even",
        "orphans",
        "overflow",
        
        "padding-after",
        "padding-after.length",
        "padding-after.conditionality",
        "padding-before",
        "padding-before.length",
        "padding-before.conditionality",
        "padding-end",
        "padding-end.length",
        "padding-end.conditionality",
        "padding-start",
        "padding-start.length",
        "padding-start.conditionality",

        "padding-bottom",
        "padding-left",
        "padding-right",
        "padding-top",
        
        "page-height",
        "page-position",
        "page-width",
        "pause-after",
        "pause-before",
        "pitch",
        "pitch-range",
        "play-during",
        "precedence",
        "provisional-distance-between-starts",
        "provisional-label-separation",
        "reference-orientation",
        "ref-id",
        "region-name",
        "relative-align",
        "relative-position",
        "rendering-intent",
        "retrieve-boundary",
        "retrieve-class-name",
        "retrieve-position",
        "richness",
        "right",
        "role",
        "rule-style",
        "rule-thickness",
        "scaling",
        "scaling-method",
        "score-spaces",
        "script",
        "show-destination",
        "source-document",

        "space-after",
        "space-after.minimum",
        "space-after.optimum",
        "space-after.maximum",
        "space-after.conditionality",
        "space-after.precedence",
        "space-before",
        "space-before.minimum",
        "space-before.optimum",
        "space-before.maximum",
        "space-before.conditionality",
        "space-before.precedence",
        "space-end",
        "space-end.minimum",
        "space-end.optimum",
        "space-end.maximum",
        "space-end.conditionality",
        "space-end.precedence",
        "space-start",
        "space-start.minimum",
        "space-start.optimum",
        "space-start.maximum",
        "space-start.conditionality",
        "space-start.precedence",

        "margin-bottom",
        "margin-left",
        "margin-right",
        "margin-top",

        "span",
        "speak",
        "speak-header",
        "speak-numeral",
        "speak-punctuation",
        "speech-rate",
        "src",
        "start-indent",
        "starting-state",
        "starts-row",
        "stress",
        "suppress-at-line-break",
        "switch-to",
        "table-layout",
        "table-omit-footer-at-break",
        "table-omit-header-at-break",
        "target-presentation-context",
        "target-processing-context",
        "target-stylesheet",
        "text-align",
        "text-align-last",
        "text-altitude",
        "text-decoration",
        "text-depth",
        "text-indent",
        "text-shadow",
        "text-transform",
        "top",
        "treat-as-word-space",
        "unicode-bidi",
        "visibility",
        "voice-family",
        "volume",
        "white-space-collapse",
        "white-space-treatment",
        "widows",
        "width",
        "word-spacing",
        "word-spacing-minimum",
        "word-spacing-optimum",
        "word-spacing-maximum",
        "word-spacing-conditionality",
        "word-spacing-precedence",
        "wrap-option",
        "writing-mode",
        "z-index"
    };

    /**
     * @param propindex <tt>int</tt> index of the FO property.
     * @return <tt>String</tt> name of the indexd FO property.
     * @exception PropertyException if the property index is invalid.
     */
    public static String getPropertyName(int propindex)
                throws PropertyException
    {
        if (propindex < 0 || propindex > LAST_PROPERTY_INDEX)
                throw new PropertyException
                        ("getPropertyName: index is invalid: " + propindex);
        return propertyNames[propindex];
    }

}
