// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Text;

namespace Fop.Util.Text;

/// <summary>
/// Represents a message template part. This interface is implemented by the various variants of
/// the single curly braces pattern (<c>{field}</c>, <c>{field,if,yes,no}</c> etc.).
/// <para>Port of the nested <c>AdvancedMessageFormat.Part</c> interface.</para>
/// </summary>
public interface IPart
{
    /// <summary>Writes the formatted part to a string builder.</summary>
    /// <param name="sb">The target string builder.</param>
    /// <param name="parameters">The parameters to work with.</param>
    void Write(StringBuilder sb, IReadOnlyDictionary<string, object?> parameters);

    /// <summary>
    /// Indicates whether there is any content that is generated by this message part.
    /// </summary>
    /// <param name="parameters">The parameters to work with.</param>
    /// <returns><c>true</c> if the part has content.</returns>
    bool IsGenerated(IReadOnlyDictionary<string, object?> parameters);
}
