File=Файл
Exit=Закончить
View=Вид
First page=Первая страница
Previous page=Предыдущая страница
Next page=Следующая страница
Last page=Последняя страница
Help=Помощь
Default zoom=Стандартный масштаб
Introduction=Введение
About=О программе
Show=Показ
Preview=Просмотр
Print=Печатать
Page=Страница
of=из
Zoom=Масштаб
Close=Закрыть
